### ISSUE TITLE
Mismatch in instructions and the code in the nameservice tutorial

### ISSUE THREAD

**Issue by hammadtq** [cosmos/sdk-tutorials#195]
The instructions at [06-keeper](https://tutorials.cosmos.network/nameservice/tutorial/06-keeper.html) asks you to create a new file at `./x/nameservice/keeper.go` while in [12-alias](https://tutorials.cosmos.network/nameservice/tutorial/12-alias.html) the tutorial is trying to import `github.com/cosmos/sdk-tutorials/nameservice/x/nameservice/internal/keeper`.

This is a general structure and import issue in all of the tutorial as in the [nameservice source code](https://github.com/cosmos/sdk-tutorials/tree/master/nameservice/x/nameservice) we have an `internal` folder inside the module but in the tutorial we are not creating one but referencing to it.

**Comment by marbar3778** [comment]
ah thank you, I apoligize for the confusion, we are finishing work a scaffolding tool to take of this for you. We hop to have it out tomorrow or monday

**Comment by mcadam** [comment]
any updates? what are the paths we should use in the alias.go file?

**Comment by mcadam** [comment]
There was quite a bit more errors than that commit, I had to fix other paths in other files too, in the tutorial the keeper and queryier are put in the package keeper, at different paths than internal, etc.

It would be nice for  someone to follow the tutorial fully https://tutorials.cosmos.network/nameservice/tutorial/00-intro.html
and then fix the errors at the end while trying to build and make sure everything works. 
In my opinion its quite important when approaching a new project like this and follow a tutorial to be able to go all the way, otherwise you lose potential users :)
