### ISSUE TITLE
[nameservice] broken import

### ISSUE THREAD

**Issue by gazhayes** [cosmos/sdk-tutorials#296]
```
cannot find package "github.com/cosmos/cosmos-sdk/x/auth/client/utils" in any of:
```

github.com/cosmos/cosmos-sdk/x/auth/client/utils doesn't exist anymore 

https://github.com/cosmos/sdk-tutorials/blob/7dccd9c5e1ed6136a334b9bcf7ab04a73627547f/nameservice/x/nameservice/client/rest/tx.go#L11

**Comment by okwme** [comment]
Hello @gazhayes thanks for making an issue.
I've just cloned the branch you mention and don't receive the error. When I click through it shows that `x/auth/client/utils` does in fact exist. The version of the SDK it is using is `v0.38.2`, is it possible you've got a issue with your `go.mod` or `go.sum` so that you're referencing the wrong version of the SDK?

**Comment by gazhayes** [comment]
Ah yeah oops. Wrong version.

Thanks!
