### ISSUE TITLE
Blog tutorial error: chain ID required but not specified

### ISSUE THREAD

**Issue by kidylee** [cosmos/sdk-tutorials#651]
Hi there,

By following the tutorial, error occurs when run below command:

``` shell
blogd tx blog create-post "My first post" "This is a post\!" --from=alice

Error: chain ID required but not specified
```

It can be fixed by adding chain id flag, but I don't think it is the way of cli be designed.

```
blogd tx blog create-post "My first post" "This is a post\!" --from=alice --chain-id="blog"
```

Correct me if I'm wrong, a cli is generated for a specific chain in intuitively, it should send tx to the chain by default. On the other hand, user could leverage the cli to send message to other chain by replacing chain-id via flag, but the risk is on their own.

Please let me know your thoughts and maybe I could contribute, thanks.

**Comment by fadeev** [comment]
Hi! Thanks for reporting this! I believe we should add `--chain-id` to the tutorial. I think in the past it used to be optional, or it had a default. In any case, the reason why it's needed is that multiple chains with different chain IDs (specified in their respective genesis files) can be launched from the same source code.

**Comment by barriebyron** [comment]
@kidylee this command is fixed in https://github.com/cosmos/sdk-tutorials/pull/662 along with some other doc styles and standards edits. We are always a work in progress. Let us know if you see anything else. 
I started the work before I noticed your awesome offer to contribute. We have plenty of opportunities for you.
Maybe next you'll be willing to try https://tutorials.cosmos.network/voter/ and help us out there?
